version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: standard

  enable:
    - revive      
    - staticcheck 
    - gosec       
    - ineffassign
    - errcheck
    - govet

  disable:
    - funlen
    - gocyclo
    - gochecknoglobals
    - gochecknoinits

  exclusions:
    presets:
        - comments
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - dupl
      - path: test/
        text: 'Error return value of `json.Unmarshal` is not checked'
        linters:
          - errcheck
      - path: internal/testhelpers/
        text: 'Error return value of.*Close.*is not checked'
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
